### Define where most of your videos and H5 files are located. The GUI uses this information as the initial folder to
### open the file browser

videos_main_path:
- /Users/senaagezo/Downloads/Oxytocin/

h5files_path:
-   /Users/senaagezo/Downloads/Oxytocin/

### Define the animals in the H5 files and the body parts that were labeled
animals:
- ind1
- ind2

body_parts:
- Nose
- leftEar
- betweenEars
- rightEar
- rightMidWaist
- leftMidWaist
- leftHip
- midHip
- rightHip
- tailStart

### Defining skeleton to plot on Videos

skeleton:
- - Nose
  - leftEar
- - Nose
  - betweenEars
- - Nose
  - rightEar
- - leftEar
  - betweenEars
- - betweenEars
  - rightEar
- - betweenEars
  - midHip
- - rightEar
  - rightMidWaist
- - rightMidWaist
  - leftMidWaist
- - rightMidWaist
  - rightHip
- - leftEar
  - leftMidWaist
- - leftMidWaist
  - leftHip
- - leftHip
  - midHip
- - midHip
  - rightHip
- - rightHip
  - tailStart
- - leftHip
  - tailStart

frames_path:
- /Users/senaagezo/Downloads/Oxytocin/labeled-data/